### PR TITLE
fix: backtrace segmentation fault

### LINKED ISSUE #12: backtrace segmentation fault
While running `mysql_install_db` I ran into the following error: 

`/QOpenSys/pkgs/bin/mysql_install_db[2]: 8628721 Memory fault(coredump)`

Examining the core file I found:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0900000000985dc0 in backtrace () from /QOpenSys/pkgs/lib/libutil.so.2(shr_64.o)
(gdb) bt
#0  0x0900000000985dc0 in backtrace () from /QOpenSys/pkgs/lib/libutil.so.2(shr_64.o)
#1  0x0000000100031c48 in sf_malloc (size=1480, my_flags=16)
    at /home/AMUSSE/rpmbuild/BUILD/mariadb-10.3.14/mysys/safemalloc.c:141
#2  0x000000010003074c in my_malloc (size=1480, my_flags=16)
    at /home/AMUSSE/rpmbuild/BUILD/mariadb-10.3.14/mysys/my_malloc.c:101
#3  0x0000000100f042ec in init_queue (queue=0x180cee7e8 <_thralarm.bss_3_+312>, max_elements=184, 
    offset_to_key=0, max_at_top=0 '�', compare=@0x1803cc4d8: 0x10129fe08 <compare_ulong>, first_cmp_arg=0x0, 
    offset_to_queue_pos=25, auto_extent=10) at /home/AMUSSE/rpmbuild/BUILD/mariadb-10.3.14/mysys/queues.c:79
#4  0x000000010129ff00 in init_thr_alarm (max_alarms=183)
    at /home/AMUSSE/rpmbuild/BUILD/mariadb-10.3.14/mysys/thr_alarm.c:92
#5  0x0000000100009dec in signal_hand (arg=0x0) at /home/AMUSSE/rpmbuild/BUILD/mariadb-10.3.14/sql/mysqld.cc:3512
#6  0x0900000000583da4 in _pthread_body () from /QOpenSys/usr/lib/libpthreads.a(shr_xpg5_64.o)
#7  0x0000000000000000 in ?? ()
```

### PR DESCRIPTION
**Pull request by abmusse**
Fixes #12

This problem affects running backtrace from pthread as the bottom of the pthread stack will always have a NULL return address.

### CODE REVIEW

**Comment by kadler** [comment]
Please note in the commit that the problem affects running backtrace from pthread as the bottom  of the pthread stack will always have a NULL return address.

File: util/backtrace.c [hunk 1]
```diff
@@ -83,7 +83,7 @@ size_t backtrace(void** frames, size_t count)
         // the displacement is verified to be the proper offset by GDB, and we
         // employ a similar heuristic.
         // XXX: What about syscalls?
-        if (lr < (void*)TEXTORG) {
+        if (lr < (void*)TEXTORGi && lr != 0) {
```
Comment (kadler) [inline util/backtrace.c:86]:
```suggestion
        if (lr < (void*)TEXTORG && lr != NULL) {
```
